
  # -------------------------------------------------------
  # Laravel Backend
  # -------------------------------------------------------
  backend:
    build:
      context: ./registrar-backend
      dockerfile: Dockerfile
    container_name: ris_backend
    restart: always
    environment:
      APP_ENV: ${APP_ENV:-production}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG:-false}
      APP_URL: ${APP_URL}
      DB_CONNECTION: mysql
      DB_HOST: ${DB_HOST}  
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      AZURE_STORAGE_NAME: ${AZURE_STORAGE_NAME}
      AZURE_STORAGE_KEY: ${AZURE_STORAGE_KEY}
      AZURE_STORAGE_CONTAINER: ${AZURE_STORAGE_CONTAINER}
      SSO_PUBLIC_KEY: ${SSO_PUBLIC_KEY}
      SSO_CLIENT_ID: ${SSO_CLIENT_ID}
    ports:
      - "8000:8000"
    networks:
      - ris_network

  # -------------------------------------------------------
  # React Frontend
  # -------------------------------------------------------
  frontend:
    build:
      context: ./registrar-frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: ris_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ris_network
  volumes:
    ris_db_data:

  networks:
    ris_network:
      driver: bridge
